{{- if .Values.deployments.azuresecrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azuresecretname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: azure-secret
    {{- with $.Values.customLabels }}
{{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  azurestorageaccountname: "{{ .Values.storageAccountName }}"
  azurestorageaccountkey: "{{ .Values.storageAccessKey }}"
{{- end }}

{{- if .Values.deployments.dbsecrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pwd
  namespace: {{ .Values.namespace }}
  labels:
    app: db-secret
    {{- with $.Values.customLabels }}
{{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.db.dbPassword }}"
{{- end }}
