{{- if .Values.deployments.serviceaccount.enabled }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceaccount }}
    {{- with $.Values.customLabels }}
{{ toYaml . | nindent 4 }}
    {{- end }}

{{- end }}
